#pragma once

/* Version info */
#define AIECAD_VERSION_MAJOR    @PROJECT_VERSION_MAJOR@
#define AIECAD_VERSION_MINOR    @PROJECT_VERSION_MINOR@
#define AIECAD_VERSION_PATCH    @PROJECT_VERSION_PATCH@
#define AIECAD_VERSION_STRING   "@PROJECT_VERSION@"
#define AIECAD_BUILD_TYPE       "@CMAKE_BUILD_TYPE@"

/* Feature detection */
#cmakedefine01 AIECAD_ENABLE_LOGGING
#cmakedefine01 AIECAD_ENABLE_ASSERTS
#cmakedefine01 AIECAD_HAVE_WEAK_SYMBOLS
#cmakedefine01 AIECAD_HAVE_PTHREAD
#cmakedefine01 AIECAD_HAVE_OPENGL

/* Graphics suppport */
#cmakedefine01 AIECAD_WINDOW_BACKEND_GLFW
#cmakedefine01 AIECAD_RENDER_API_OPENGL